### ISSUE TITLE
Announce IRC joins with NOTICE

### ISSUE THREAD

**Issue by stigok** [flexd/b2s#1]
As I'm on the IRC side of this bridge, it would be nice to have the Slack joins and parts be announced on IRC as `NOTICE` instead of `PRIVMSG`. It makes for better handling of client message notifications and coherence with IRC protocol semantics in general.

I'd be happy to provide a PR if you agree with my rationale :)

**Comment by flexd** [comment]
Hey, feel free to make the change! If you are looking into the code base anyway I have been meaning to make a change to better display how file uploads and posted pictures are handled (maybe even re-hosting them, though I think it might be possible to get a public url from slack)
